name: elfer
description: A tracker UI for the Korg Electribe 2
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  bonsai: ^1.0.1
  cupertino_icons: ^1.0.2
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_midi_command:
    git:
      url: https://github.com/maks/FlutterMidiCommand
      ref: dart-ffi-linux-platform
  # flutter_midi_command: ^0.4.2
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  ninja_hex: ^2.0.0
  tonic: ^0.2.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 89c350f787e1d7bff12b3517e5671146211ee70e

dev_dependencies:
  build_runner: ^2.1.7
  ffigen: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    # test data for now
    - assets/e2pattern.dat  

ffigen:
  name: "elecmidi"
  output: "lib/tracker/e2_data/elecmidi_generated.dart"
  headers:
    entry-points:
      - "elecmidi/elecmidi.h"
  llvm-path:
    - "/usr/lib/llvm-12"
  # compiler-opts: "-I/usr/lib/llvm-12/include/ -L/usr/lib/llvm-12/lib/
  #   -I/usr/local/opt/llvm/include/ -Wno-nullability-completeness"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
