name: elfer
description: A new Flutter project.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  bonsai: ^1.0.1
  cupertino_icons: ^1.0.2
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_midi_command:
    path: ../FlutterMidiCommand
  ninja_hex: ^2.0.0
  tonic: ^0.2.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 89c350f787e1d7bff12b3517e5671146211ee70e

dev_dependencies:
  ffigen: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

ffigen:
  name: "elecmidi"
  output: "lib/elecmidi_generated.dart"
  headers:
    entry-points:
      - "elecmidi/elecmidi.h"
  llvm-path:
    - "/usr/lib/llvm-12"
  # compiler-opts: "-I/usr/lib/llvm-12/include/ -L/usr/lib/llvm-12/lib/
  #   -I/usr/local/opt/llvm/include/ -Wno-nullability-completeness"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
